### ISSUE TITLE
Adopt or edit stylesheet for prettier components

### ISSUE THREAD

**Issue by surchs** [neurodatascience/concept_query#20]
Use bootstrap or custom stylesheets to improve the look of our interface components.

**Comment by jarmoza** [comment]
Currently being addressed in https://github.com/neurodatascience/concept_query/tree/dataset-cards branch

**Comment by jarmoza** [comment]
Static css files for the demo were added in `query_prototype/static/css` with commit https://github.com/neurodatascience/concept_query/commit/6efd98c79216abe34209eaae53ba06191c71fbfc
