### ISSUE TITLE
Scripts to query database for all values of query fields and generate choices Python script

### ISSUE THREAD

**Issue by jarmoza** [neurodatascience/concept_query#27]
We need two script files.

1. Queries the database (when needed/when the database changes) for all possible values of the query field dropdowns in the demo. Currently: gender, modality, diagnosis, and (in the future) control status. That script generates the second script...
2. query_choices.py that includes the values in 2D tuple format across several fields with human readable and db names. See example in: https://github.com/neurodatascience/concept_query/blob/main/query_prototype/query_choices.py

**Comment by jarmoza** [comment]
@surchs Here's the documentation on the Django choices field for models:

https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.Field.choices

Key sentence: "The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name."

**Comment by surchs** [comment]
Aha, thanks @jarmoza. That's indeed good to know! Thanks for the find / clarification
