### ISSUE TITLE
When a query had only None/NaN results for an entire domain, the corresponding column is missing from the results

### ISSUE THREAD

**Issue by surchs** [neurodatascience/concept_query#47]
We use the SPARQL query response json and turn it into a pandas dataframe.
We expect that all columns are present (although they can have missing values). The problem is that SPARQL does not return a column / json key if the values for this column would be None for all rows. 

In other words: if my cohort does not include any non-None values for `diagnosis`, then the `diagnosis` column would be absent from the returned pandas dataframe. If I then go and include a diagnosis-based cohort constraint, I'll get a key error, because the column I'm trying to reference isn't there.

**Comment by surchs** [comment]
The fix to this is easy: We can just define a list of columns we want to have when we create the pandas dataframe. columns that do not match any of the keys in the data dictionary will just end up being empty. 

The risk here is that if we change the SPARQL variable names but don't update the forced column names accordingly, we will not show the actual results and instead force empty columns in the table.

**Comment by jarmoza** [comment]
Some kind of recipe (e.g. script), programmatic and/or otherwise for updating the graph database would be useful then – with accompanying documentation of it.
